09:42:19 - 21ArvoreBinaria - ERROR: /reports/ds.seed5482.JTExpert/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '21ArvoreBinaria/reports/ds.seed5482.JTExpert/index.html'

09:47:20 - 21ArvoreBinaria - ERROR: /reports/ds.seed5482.JTExpert/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '21ArvoreBinaria/reports/ds.seed5482.JTExpert/index.html'

09:47:54 - 21ArvoreBinaria - ERROR: /reports/ds.seed5482.JTExpert/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '21ArvoreBinaria/reports/ds.seed5482.JTExpert/index.html'

09:48:22 - 21ArvoreBinaria - ERROR: /reports/ds.seed5482.JTExpert/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '21ArvoreBinaria/reports/ds.seed5482.JTExpert/index.html'

10:39:18 - 22TabelaHash - ERROR: /reports/ds.seed7992.JTExpert/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed7992.JTExpert/index.html'

10:40:06 - 25Grafo - ERROR: /reports/ds.seed7992.JTExpert/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '25Grafo/reports/ds.seed7992.JTExpert/index.html'

10:44:37 - 12Lista - ERROR: /reports/ds.seed9006.JTExpert/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '12Lista/reports/ds.seed9006.JTExpert/index.html'

10:46:47 - 20Tabela - ERROR: /reports/ds.seed9006.JTExpert/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '20Tabela/reports/ds.seed9006.JTExpert/index.html'

11:20:11 - 22TabelaHash - ERROR: /reports/ds.seed7992.JTExpert/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed7992.JTExpert/index.html'

11:20:11 - 25Grafo - ERROR: /reports/ds.seed7992.JTExpert/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '25Grafo/reports/ds.seed7992.JTExpert/index.html'

11:21:55 - 25Grafo - ERROR: /reports/ds.seed7992.JTExpert/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '25Grafo/reports/ds.seed7992.JTExpert/index.html'

11:25:17 - 20Tabela - ERROR: /reports/ds.seed9006.JTExpert/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '20Tabela/reports/ds.seed9006.JTExpert/index.html'

14:11:50 - 01Max - ERROR: /reports/ds.seed1448.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '01Max/reports/ds.seed1448.Randoop/index.html'

14:11:58 - 02MaxMin - ERROR: /reports/ds.seed1448.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '02MaxMin/reports/ds.seed1448.Randoop/index.html'

14:12:05 - 03MaxMin - ERROR: /reports/ds.seed1448.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '03MaxMin/reports/ds.seed1448.Randoop/index.html'

14:12:13 - 04MaxMin - ERROR: /reports/ds.seed1448.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '04MaxMin/reports/ds.seed1448.Randoop/index.html'

14:12:18 - 05Ordenacao - ERROR: /reports/ds.seed1448.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '05Ordenacao/reports/ds.seed1448.Randoop/index.html'

14:12:18 - 06Fibonacci - ERROR: /reports/ds.seed1448.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '06Fibonacci/reports/ds.seed1448.Randoop/index.html'

14:12:18 - 07Fibonacci - ERROR: /reports/ds.seed1448.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '07Fibonacci/reports/ds.seed1448.Randoop/index.html'

14:12:19 - 08MaxMin - ERROR: /reports/ds.seed1448.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '08MaxMin/reports/ds.seed1448.Randoop/index.html'

14:12:19 - 09Ordenacao - ERROR: /reports/ds.seed1448.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '09Ordenacao/reports/ds.seed1448.Randoop/index.html'

14:12:19 - 10AvaliaMultMatrizes - ERROR: /reports/ds.seed1448.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '10AvaliaMultMatrizes/reports/ds.seed1448.Randoop/index.html'

14:12:19 - 11ListArray - ERROR: /reports/ds.seed1448.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '11ListArray/reports/ds.seed1448.Randoop/index.html'

14:12:19 - 12Lista - ERROR: /reports/ds.seed1448.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '12Lista/reports/ds.seed1448.Randoop/index.html'

14:12:19 - 13Pilha - ERROR: /reports/ds.seed1448.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '13Pilha/reports/ds.seed1448.Randoop/index.html'

14:12:19 - 14Pilha - ERROR: /reports/ds.seed1448.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '14Pilha/reports/ds.seed1448.Randoop/index.html'

14:12:19 - 15Fila - ERROR: /reports/ds.seed1448.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '15Fila/reports/ds.seed1448.Randoop/index.html'

14:12:19 - 16Fila - ERROR: /reports/ds.seed1448.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '16Fila/reports/ds.seed1448.Randoop/index.html'

14:12:19 - 17Ordenacao - ERROR: /reports/ds.seed1448.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '17Ordenacao/reports/ds.seed1448.Randoop/index.html'

14:12:19 - 18FPHeapMax - ERROR: /reports/ds.seed1448.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '18FPHeapMax/reports/ds.seed1448.Randoop/index.html'

14:12:20 - 19FPHeapMin - ERROR: /reports/ds.seed1448.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '19FPHeapMin/reports/ds.seed1448.Randoop/index.html'

14:12:20 - 20Tabela - ERROR: /reports/ds.seed1448.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '20Tabela/reports/ds.seed1448.Randoop/index.html'

14:12:20 - 21ArvoreBinaria - ERROR: /reports/ds.seed1448.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '21ArvoreBinaria/reports/ds.seed1448.Randoop/index.html'

14:12:20 - 22TabelaHash - ERROR: /reports/ds.seed1448.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed1448.Randoop/index.html'

14:12:20 - 23TabelaHash - ERROR: /reports/ds.seed1448.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '23TabelaHash/reports/ds.seed1448.Randoop/index.html'

14:12:20 - 24Grafo - ERROR: /reports/ds.seed1448.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '24Grafo/reports/ds.seed1448.Randoop/index.html'

14:12:20 - 25Grafo - ERROR: /reports/ds.seed1448.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '25Grafo/reports/ds.seed1448.Randoop/index.html'

14:12:20 - 26Grafo - ERROR: /reports/ds.seed1448.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '26Grafo/reports/ds.seed1448.Randoop/index.html'

14:12:20 - 27Grafo - ERROR: /reports/ds.seed1448.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '27Grafo/reports/ds.seed1448.Randoop/index.html'

14:12:20 - 28BuscaEmLargura - ERROR: /reports/ds.seed1448.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '28BuscaEmLargura/reports/ds.seed1448.Randoop/index.html'

14:12:20 - 29Grafo - ERROR: /reports/ds.seed1448.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '29Grafo/reports/ds.seed1448.Randoop/index.html'

14:12:20 - 30Lista - ERROR: /reports/ds.seed1448.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '30Lista/reports/ds.seed1448.Randoop/index.html'

14:12:20 - 31CasamentoExato - ERROR: /reports/ds.seed1448.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '31CasamentoExato/reports/ds.seed1448.Randoop/index.html'

14:12:20 - 32CasamentoAproximado - ERROR: /reports/ds.seed1448.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '32CasamentoAproximado/reports/ds.seed1448.Randoop/index.html'

14:12:21 - 33Identifier - ERROR: /reports/ds.seed1448.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 49, in <module>
    output.write(covs[2].text.split("/")[0].strip() + ";")
IndexError: list index out of range

14:45:02 - 22TabelaHash - ERROR: /reports/ds.seed1448.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed1448.Randoop/index.html'

14:45:16 - 23TabelaHash - ERROR: /reports/ds.seed1448.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '23TabelaHash/reports/ds.seed1448.Randoop/index.html'

16:30:50 - 22TabelaHash - ERROR: /reports/ds.seed1448.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed1448.Randoop/index.html'

16:30:51 - 23TabelaHash - ERROR: /reports/ds.seed1448.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '23TabelaHash/reports/ds.seed1448.Randoop/index.html'

16:37:10 - 22TabelaHash - ERROR: /reports/ds.seed1448.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed1448.Randoop/index.html'

16:37:14 - 23TabelaHash - ERROR: /reports/ds.seed1448.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '23TabelaHash/reports/ds.seed1448.Randoop/index.html'

16:37:44 - 22TabelaHash - ERROR: /reports/ds.seed1448.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed1448.Randoop/index.html'

16:37:50 - 23TabelaHash - ERROR: /reports/ds.seed1448.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '23TabelaHash/reports/ds.seed1448.Randoop/index.html'

16:39:36 - 22TabelaHash - ERROR: /reports/ds.seed1448.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed1448.Randoop/index.html'

16:39:42 - 23TabelaHash - ERROR: /reports/ds.seed1448.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '23TabelaHash/reports/ds.seed1448.Randoop/index.html'

16:39:54 - 22TabelaHash - ERROR: /reports/ds.seed1448.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed1448.Randoop/index.html'

16:40:00 - 23TabelaHash - ERROR: /reports/ds.seed1448.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '23TabelaHash/reports/ds.seed1448.Randoop/index.html'

16:40:36 - 22TabelaHash - ERROR: /reports/ds.seed1448.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed1448.Randoop/index.html'

16:40:43 - 23TabelaHash - ERROR: /reports/ds.seed1448.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '23TabelaHash/reports/ds.seed1448.Randoop/index.html'

16:41:09 - 22TabelaHash - ERROR: /reports/ds.seed1448.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed1448.Randoop/index.html'

16:41:16 - 23TabelaHash - ERROR: /reports/ds.seed1448.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '23TabelaHash/reports/ds.seed1448.Randoop/index.html'

16:41:23 - 22TabelaHash - ERROR: /reports/ds.seed1448.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed1448.Randoop/index.html'

16:41:30 - 23TabelaHash - ERROR: /reports/ds.seed1448.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '23TabelaHash/reports/ds.seed1448.Randoop/index.html'

16:42:02 - 22TabelaHash - ERROR: /reports/ds.seed1448.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed1448.Randoop/index.html'

16:42:09 - 23TabelaHash - ERROR: /reports/ds.seed1448.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '23TabelaHash/reports/ds.seed1448.Randoop/index.html'

16:42:36 - 22TabelaHash - ERROR: /reports/ds.seed1448.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed1448.Randoop/index.html'

16:42:42 - 23TabelaHash - ERROR: /reports/ds.seed1448.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '23TabelaHash/reports/ds.seed1448.Randoop/index.html'

16:43:06 - 22TabelaHash - ERROR: /reports/ds.seed1448.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed1448.Randoop/index.html'

16:43:13 - 23TabelaHash - ERROR: /reports/ds.seed1448.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '23TabelaHash/reports/ds.seed1448.Randoop/index.html'

16:43:39 - 22TabelaHash - ERROR: /reports/ds.seed1448.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed1448.Randoop/index.html'

16:43:45 - 23TabelaHash - ERROR: /reports/ds.seed1448.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '23TabelaHash/reports/ds.seed1448.Randoop/index.html'

16:44:48 - 22TabelaHash - ERROR: /reports/ds.seed1448.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed1448.Randoop/index.html'

16:55:53 - 22TabelaHash - ERROR: /reports/ds.seed1448.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed1448.Randoop/index.html'

16:56:31 - 22TabelaHash - ERROR: /reports/ds.seed1448.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed1448.Randoop/index.html'

16:59:35 - 22TabelaHash - ERROR: /reports/ds.seed1448.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed1448.Randoop/index.html'

17:01:11 - 22TabelaHash - ERROR: /reports/ds.seed1448.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed1448.Randoop/index.html'

17:05:49 - 22TabelaHash - ERROR: /reports/ds.seed1448.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed1448.Randoop/index.html'

17:07:03 - 22TabelaHash - ERROR: /reports/ds.seed1448.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed1448.Randoop/index.html'

17:18:56 - 22TabelaHash - ERROR: /reports/ds.seed1448.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed1448.Randoop/index.html'

17:20:24 - 22TabelaHash - ERROR: /reports/ds.seed1448.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed1448.Randoop/index.html'

17:21:45 - 22TabelaHash - ERROR: /reports/ds.seed1448.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed1448.Randoop/index.html'

17:23:59 - 22TabelaHash - ERROR: /reports/ds.seed1448.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed1448.Randoop/index.html'

17:24:53 - 22TabelaHash - ERROR: /reports/ds.seed1448.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed1448.Randoop/index.html'

17:25:27 - 22TabelaHash - ERROR: /reports/ds.seed1448.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed1448.Randoop/index.html'

17:26:05 - 22TabelaHash - ERROR: /reports/ds.seed1448.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed1448.Randoop/index.html'

17:26:40 - 22TabelaHash - ERROR: /reports/ds.seed1448.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed1448.Randoop/index.html'

22:17:18 - 22TabelaHash - ERROR: /reports/ds.seed5311.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed5311.Randoop/index.html'

22:58:35 - 22TabelaHash - ERROR: /reports/ds.seed5482.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed5482.Randoop/index.html'

23:36:14 - 22TabelaHash - ERROR: /reports/ds.seed5503.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed5503.Randoop/index.html'

00:13:06 - 22TabelaHash - ERROR: /reports/ds.seed5831.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed5831.Randoop/index.html'

00:50:44 - 22TabelaHash - ERROR: /reports/ds.seed5838.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed5838.Randoop/index.html'

01:27:16 - 22TabelaHash - ERROR: /reports/ds.seed6733.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed6733.Randoop/index.html'

01:27:26 - 23TabelaHash - ERROR: /reports/ds.seed6733.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '23TabelaHash/reports/ds.seed6733.Randoop/index.html'

02:02:40 - 22TabelaHash - ERROR: /reports/ds.seed7992.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed7992.Randoop/index.html'

02:40:54 - 22TabelaHash - ERROR: /reports/ds.seed9006.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed9006.Randoop/index.html'

02:41:08 - 23TabelaHash - ERROR: /reports/ds.seed9006.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '23TabelaHash/reports/ds.seed9006.Randoop/index.html'

03:17:41 - 22TabelaHash - ERROR: /reports/ds.seed9121.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed9121.Randoop/index.html'

03:17:55 - 23TabelaHash - ERROR: /reports/ds.seed9121.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '23TabelaHash/reports/ds.seed9121.Randoop/index.html'

09:25:41 - 22TabelaHash - ERROR: /reports/ds.seed5482.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed5482.Randoop/index.html'

09:27:17 - 22TabelaHash - ERROR: /reports/ds.seed5482.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed5482.Randoop/index.html'

09:28:05 - 22TabelaHash - ERROR: /reports/ds.seed5482.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed5482.Randoop/index.html'

09:29:02 - 22TabelaHash - ERROR: /reports/ds.seed5482.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed5482.Randoop/index.html'

09:29:45 - 22TabelaHash - ERROR: /reports/ds.seed5482.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed5482.Randoop/index.html'

09:30:16 - 22TabelaHash - ERROR: /reports/ds.seed5482.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed5482.Randoop/index.html'

09:32:54 - 22TabelaHash - ERROR: /reports/ds.seed5503.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed5503.Randoop/index.html'

09:34:43 - 22TabelaHash - ERROR: /reports/ds.seed5503.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed5503.Randoop/index.html'

09:35:21 - 22TabelaHash - ERROR: /reports/ds.seed5503.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed5503.Randoop/index.html'

09:58:03 - 22TabelaHash - ERROR: /reports/ds.seed5831.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed5831.Randoop/index.html'

09:59:46 - 22TabelaHash - ERROR: /reports/ds.seed5831.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed5831.Randoop/index.html'

10:00:28 - 22TabelaHash - ERROR: /reports/ds.seed5831.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed5831.Randoop/index.html'

10:01:28 - 22TabelaHash - ERROR: /reports/ds.seed5831.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed5831.Randoop/index.html'

10:02:48 - 22TabelaHash - ERROR: /reports/ds.seed5831.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed5831.Randoop/index.html'

10:03:17 - 22TabelaHash - ERROR: /reports/ds.seed5831.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed5831.Randoop/index.html'

10:03:48 - 22TabelaHash - ERROR: /reports/ds.seed5831.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed5831.Randoop/index.html'

10:04:34 - 22TabelaHash - ERROR: /reports/ds.seed5831.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed5831.Randoop/index.html'

10:13:52 - 22TabelaHash - ERROR: /reports/ds.seed5838.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed5838.Randoop/index.html'

10:14:37 - 22TabelaHash - ERROR: /reports/ds.seed5838.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed5838.Randoop/index.html'

10:30:11 - 22TabelaHash - ERROR: /reports/ds.seed5838.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed5838.Randoop/index.html'

10:30:46 - 22TabelaHash - ERROR: /reports/ds.seed5838.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed5838.Randoop/index.html'

10:31:27 - 22TabelaHash - ERROR: /reports/ds.seed5838.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed5838.Randoop/index.html'

10:32:19 - 22TabelaHash - ERROR: /reports/ds.seed5838.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed5838.Randoop/index.html'

12:02:37 - 22TabelaHash - ERROR: /reports/ds.seed6733.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed6733.Randoop/index.html'

12:02:49 - 23TabelaHash - ERROR: /reports/ds.seed6733.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '23TabelaHash/reports/ds.seed6733.Randoop/index.html'

12:03:53 - 22TabelaHash - ERROR: /reports/ds.seed6733.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed6733.Randoop/index.html'

12:04:54 - 22TabelaHash - ERROR: /reports/ds.seed6733.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed6733.Randoop/index.html'

12:08:14 - 22TabelaHash - ERROR: /reports/ds.seed6733.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed6733.Randoop/index.html'

12:08:45 - 22TabelaHash - ERROR: /reports/ds.seed6733.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed6733.Randoop/index.html'

12:08:59 - 22TabelaHash - ERROR: /reports/ds.seed6733.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed6733.Randoop/index.html'

13:41:20 - 22TabelaHash - ERROR: /reports/ds.seed7992.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed7992.Randoop/index.html'

13:44:02 - 22TabelaHash - ERROR: /reports/ds.seed7992.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed7992.Randoop/index.html'

13:45:01 - 22TabelaHash - ERROR: /reports/ds.seed7992.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed7992.Randoop/index.html'

13:46:41 - 22TabelaHash - ERROR: /reports/ds.seed7992.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed7992.Randoop/index.html'

13:48:34 - 22TabelaHash - ERROR: /reports/ds.seed7992.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed7992.Randoop/index.html'

13:49:32 - 22TabelaHash - ERROR: /reports/ds.seed7992.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed7992.Randoop/index.html'

13:50:07 - 22TabelaHash - ERROR: /reports/ds.seed7992.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed7992.Randoop/index.html'

13:52:32 - 22TabelaHash - ERROR: /reports/ds.seed7992.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed7992.Randoop/index.html'

14:18:25 - 22TabelaHash - ERROR: /reports/ds.seed9006.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed9006.Randoop/index.html'

14:19:46 - 22TabelaHash - ERROR: /reports/ds.seed9006.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed9006.Randoop/index.html'

14:20:53 - 22TabelaHash - ERROR: /reports/ds.seed9006.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed9006.Randoop/index.html'

14:21:31 - 22TabelaHash - ERROR: /reports/ds.seed9006.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed9006.Randoop/index.html'

14:22:36 - 22TabelaHash - ERROR: /reports/ds.seed9006.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed9006.Randoop/index.html'

14:23:17 - 22TabelaHash - ERROR: /reports/ds.seed9006.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed9006.Randoop/index.html'

14:24:15 - 22TabelaHash - ERROR: /reports/ds.seed9006.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed9006.Randoop/index.html'

14:25:07 - 22TabelaHash - ERROR: /reports/ds.seed9006.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed9006.Randoop/index.html'

14:31:34 - 22TabelaHash - ERROR: /reports/ds.seed9121.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed9121.Randoop/index.html'

14:34:49 - 22TabelaHash - ERROR: /reports/ds.seed9121.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed9121.Randoop/index.html'

14:35:16 - 22TabelaHash - ERROR: /reports/ds.seed9121.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed9121.Randoop/index.html'

14:37:19 - 23TabelaHash - ERROR: /reports/ds.seed9121.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '23TabelaHash/reports/ds.seed9121.Randoop/index.html'

14:38:16 - 23TabelaHash - ERROR: /reports/ds.seed9121.Randoop/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '23TabelaHash/reports/ds.seed9121.Randoop/index.html'

16:12:33 - 10AvaliaMultMatrizes - ERROR: /reports/ds.seed1448.AllSmart/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '10AvaliaMultMatrizes/reports/ds.seed1448.AllSmart/index.html'

16:13:00 - 11ListArray - ERROR: /reports/ds.seed1448.AllSmart/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '11ListArray/reports/ds.seed1448.AllSmart/index.html'

16:20:18 - 22TabelaHash - ERROR: /reports/ds.seed1448.AllSmart/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed1448.AllSmart/index.html'

16:20:40 - 23TabelaHash - ERROR: /reports/ds.seed1448.AllSmart/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '23TabelaHash/reports/ds.seed1448.AllSmart/index.html'

16:36:52 - 10AvaliaMultMatrizes - ERROR: /reports/ds.seed5311.AllSmart/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '10AvaliaMultMatrizes/reports/ds.seed5311.AllSmart/index.html'

16:39:20 - 14Pilha - ERROR: /reports/ds.seed5311.AllSmart/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '14Pilha/reports/ds.seed5311.AllSmart/index.html'

16:40:07 - 16Fila - ERROR: /reports/ds.seed5311.AllSmart/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '16Fila/reports/ds.seed5311.AllSmart/index.html'

16:44:07 - 23TabelaHash - ERROR: /reports/ds.seed5311.AllSmart/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '23TabelaHash/reports/ds.seed5311.AllSmart/index.html'

16:55:53 - 10AvaliaMultMatrizes - ERROR: /reports/ds.seed5482.AllSmart/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '10AvaliaMultMatrizes/reports/ds.seed5482.AllSmart/index.html'

16:58:43 - 15Fila - ERROR: /reports/ds.seed5482.AllSmart/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '15Fila/reports/ds.seed5482.AllSmart/index.html'

17:01:26 - 19FPHeapMin - ERROR: /reports/ds.seed5482.AllSmart/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '19FPHeapMin/reports/ds.seed5482.AllSmart/index.html'

17:05:01 - 26Grafo - ERROR: /reports/ds.seed5482.AllSmart/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '26Grafo/reports/ds.seed5482.AllSmart/index.html'

17:06:10 - 29Grafo - ERROR: /reports/ds.seed5482.AllSmart/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '29Grafo/reports/ds.seed5482.AllSmart/index.html'

17:14:39 - 10AvaliaMultMatrizes - ERROR: /reports/ds.seed5503.AllSmart/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '10AvaliaMultMatrizes/reports/ds.seed5503.AllSmart/index.html'

17:20:32 - 20Tabela - ERROR: /reports/ds.seed5503.AllSmart/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '20Tabela/reports/ds.seed5503.AllSmart/index.html'

17:21:40 - 23TabelaHash - ERROR: /reports/ds.seed5503.AllSmart/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '23TabelaHash/reports/ds.seed5503.AllSmart/index.html'

17:33:26 - 10AvaliaMultMatrizes - ERROR: /reports/ds.seed5831.AllSmart/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '10AvaliaMultMatrizes/reports/ds.seed5831.AllSmart/index.html'

17:40:42 - 22TabelaHash - ERROR: /reports/ds.seed5831.AllSmart/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed5831.AllSmart/index.html'

17:42:49 - 26Grafo - ERROR: /reports/ds.seed5831.AllSmart/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '26Grafo/reports/ds.seed5831.AllSmart/index.html'

17:53:13 - 10AvaliaMultMatrizes - ERROR: /reports/ds.seed5838.AllSmart/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '10AvaliaMultMatrizes/reports/ds.seed5838.AllSmart/index.html'

17:55:43 - 14Pilha - ERROR: /reports/ds.seed5838.AllSmart/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '14Pilha/reports/ds.seed5838.AllSmart/index.html'

18:13:31 - 10AvaliaMultMatrizes - ERROR: /reports/ds.seed6733.AllSmart/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '10AvaliaMultMatrizes/reports/ds.seed6733.AllSmart/index.html'

18:16:00 - 14Pilha - ERROR: /reports/ds.seed6733.AllSmart/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '14Pilha/reports/ds.seed6733.AllSmart/index.html'

18:20:30 - 22TabelaHash - ERROR: /reports/ds.seed6733.AllSmart/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed6733.AllSmart/index.html'

18:27:56 - 28BuscaEmLargura - ERROR: /reports/ds.seed6733.AllSmart/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '28BuscaEmLargura/reports/ds.seed6733.AllSmart/index.html'

18:36:59 - 10AvaliaMultMatrizes - ERROR: /reports/ds.seed7992.AllSmart/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '10AvaliaMultMatrizes/reports/ds.seed7992.AllSmart/index.html'

18:37:28 - 11ListArray - ERROR: /reports/ds.seed7992.AllSmart/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '11ListArray/reports/ds.seed7992.AllSmart/index.html'

18:44:54 - 24Grafo - ERROR: /reports/ds.seed7992.AllSmart/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '24Grafo/reports/ds.seed7992.AllSmart/index.html'

19:00:39 - 10AvaliaMultMatrizes - ERROR: /reports/ds.seed9006.AllSmart/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '10AvaliaMultMatrizes/reports/ds.seed9006.AllSmart/index.html'

19:01:39 - 12Lista - ERROR: /reports/ds.seed9006.AllSmart/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '12Lista/reports/ds.seed9006.AllSmart/index.html'

19:02:11 - 13Pilha - ERROR: /reports/ds.seed9006.AllSmart/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '13Pilha/reports/ds.seed9006.AllSmart/index.html'

19:16:28 - 28BuscaEmLargura - ERROR: /reports/ds.seed9006.AllSmart/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '28BuscaEmLargura/reports/ds.seed9006.AllSmart/index.html'

19:20:34 - 33Identifier - ERROR: /reports/ds.seed9006.AllSmart/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '33Identifier/reports/ds.seed9006.AllSmart/index.html'

19:27:54 - 10AvaliaMultMatrizes - ERROR: /reports/ds.seed9121.AllSmart/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '10AvaliaMultMatrizes/reports/ds.seed9121.AllSmart/index.html'

19:30:15 - 14Pilha - ERROR: /reports/ds.seed9121.AllSmart/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '14Pilha/reports/ds.seed9121.AllSmart/index.html'

22:23:15 - 10AvaliaMultMatrizes - ERROR: /reports/ds.seed1448.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '10AvaliaMultMatrizes/reports/ds.seed1448.All/index.html'

22:23:39 - 11ListArray - ERROR: /reports/ds.seed1448.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '11ListArray/reports/ds.seed1448.All/index.html'

22:30:58 - 19FPHeapMin - ERROR: /reports/ds.seed1448.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '19FPHeapMin/reports/ds.seed1448.All/index.html'

22:33:00 - 22TabelaHash - ERROR: /reports/ds.seed1448.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed1448.All/index.html'

22:33:14 - 23TabelaHash - ERROR: /reports/ds.seed1448.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '23TabelaHash/reports/ds.seed1448.All/index.html'

23:00:00 - 10AvaliaMultMatrizes - ERROR: /reports/ds.seed5311.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '10AvaliaMultMatrizes/reports/ds.seed5311.All/index.html'

23:02:54 - 14Pilha - ERROR: /reports/ds.seed5311.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '14Pilha/reports/ds.seed5311.All/index.html'

23:03:44 - 16Fila - ERROR: /reports/ds.seed5311.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '16Fila/reports/ds.seed5311.All/index.html'

23:07:46 - 19FPHeapMin - ERROR: /reports/ds.seed5311.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '19FPHeapMin/reports/ds.seed5311.All/index.html'

23:09:47 - 22TabelaHash - ERROR: /reports/ds.seed5311.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed5311.All/index.html'

23:10:01 - 23TabelaHash - ERROR: /reports/ds.seed5311.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '23TabelaHash/reports/ds.seed5311.All/index.html'

23:38:11 - 10AvaliaMultMatrizes - ERROR: /reports/ds.seed5482.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '10AvaliaMultMatrizes/reports/ds.seed5482.All/index.html'

23:41:42 - 15Fila - ERROR: /reports/ds.seed5482.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '15Fila/reports/ds.seed5482.All/index.html'

23:48:38 - 22TabelaHash - ERROR: /reports/ds.seed5482.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed5482.All/index.html'

23:55:31 - 26Grafo - ERROR: /reports/ds.seed5482.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '26Grafo/reports/ds.seed5482.All/index.html'

23:57:27 - 29Grafo - ERROR: /reports/ds.seed5482.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '29Grafo/reports/ds.seed5482.All/index.html'

00:15:00 - 10AvaliaMultMatrizes - ERROR: /reports/ds.seed5503.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '10AvaliaMultMatrizes/reports/ds.seed5503.All/index.html'

00:24:14 - 20Tabela - ERROR: /reports/ds.seed5503.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '20Tabela/reports/ds.seed5503.All/index.html'

00:25:47 - 22TabelaHash - ERROR: /reports/ds.seed5503.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed5503.All/index.html'

00:26:02 - 23TabelaHash - ERROR: /reports/ds.seed5503.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '23TabelaHash/reports/ds.seed5503.All/index.html'

00:54:08 - 10AvaliaMultMatrizes - ERROR: /reports/ds.seed5831.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '10AvaliaMultMatrizes/reports/ds.seed5831.All/index.html'

01:05:36 - 22TabelaHash - ERROR: /reports/ds.seed5831.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed5831.All/index.html'

01:12:34 - 26Grafo - ERROR: /reports/ds.seed5831.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '26Grafo/reports/ds.seed5831.All/index.html'

01:33:26 - 10AvaliaMultMatrizes - ERROR: /reports/ds.seed5838.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '10AvaliaMultMatrizes/reports/ds.seed5838.All/index.html'

01:36:24 - 14Pilha - ERROR: /reports/ds.seed5838.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '14Pilha/reports/ds.seed5838.All/index.html'

01:41:23 - 19FPHeapMin - ERROR: /reports/ds.seed5838.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '19FPHeapMin/reports/ds.seed5838.All/index.html'

02:13:10 - 10AvaliaMultMatrizes - ERROR: /reports/ds.seed6733.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '10AvaliaMultMatrizes/reports/ds.seed6733.All/index.html'

02:16:04 - 14Pilha - ERROR: /reports/ds.seed6733.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '14Pilha/reports/ds.seed6733.All/index.html'

02:20:58 - 19FPHeapMin - ERROR: /reports/ds.seed6733.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '19FPHeapMin/reports/ds.seed6733.All/index.html'

02:23:11 - 22TabelaHash - ERROR: /reports/ds.seed6733.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed6733.All/index.html'

02:23:25 - 23TabelaHash - ERROR: /reports/ds.seed6733.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '23TabelaHash/reports/ds.seed6733.All/index.html'

02:28:52 - 26Grafo - ERROR: /reports/ds.seed6733.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '26Grafo/reports/ds.seed6733.All/index.html'

02:30:01 - 28BuscaEmLargura - ERROR: /reports/ds.seed6733.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '28BuscaEmLargura/reports/ds.seed6733.All/index.html'

02:48:52 - 10AvaliaMultMatrizes - ERROR: /reports/ds.seed7992.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '10AvaliaMultMatrizes/reports/ds.seed7992.All/index.html'

02:49:17 - 11ListArray - ERROR: /reports/ds.seed7992.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '11ListArray/reports/ds.seed7992.All/index.html'

03:01:56 - 24Grafo - ERROR: /reports/ds.seed7992.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '24Grafo/reports/ds.seed7992.All/index.html'

03:03:42 - 26Grafo - ERROR: /reports/ds.seed7992.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '26Grafo/reports/ds.seed7992.All/index.html'

03:23:52 - 10AvaliaMultMatrizes - ERROR: /reports/ds.seed9006.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '10AvaliaMultMatrizes/reports/ds.seed9006.All/index.html'

03:25:10 - 12Lista - ERROR: /reports/ds.seed9006.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '12Lista/reports/ds.seed9006.All/index.html'

03:25:44 - 13Pilha - ERROR: /reports/ds.seed9006.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '13Pilha/reports/ds.seed9006.All/index.html'

03:34:19 - 22TabelaHash - ERROR: /reports/ds.seed9006.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed9006.All/index.html'

03:41:56 - 26Grafo - ERROR: /reports/ds.seed9006.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '26Grafo/reports/ds.seed9006.All/index.html'

03:43:03 - 28BuscaEmLargura - ERROR: /reports/ds.seed9006.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '28BuscaEmLargura/reports/ds.seed9006.All/index.html'

04:02:14 - 10AvaliaMultMatrizes - ERROR: /reports/ds.seed9121.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '10AvaliaMultMatrizes/reports/ds.seed9121.All/index.html'

04:05:08 - 14Pilha - ERROR: /reports/ds.seed9121.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '14Pilha/reports/ds.seed9121.All/index.html'

04:12:46 - 22TabelaHash - ERROR: /reports/ds.seed9121.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed9121.All/index.html'

04:13:01 - 23TabelaHash - ERROR: /reports/ds.seed9121.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '23TabelaHash/reports/ds.seed9121.All/index.html'

18:24:40 - 10AvaliaMultMatrizes - ERROR: /reports/ds.seed1448.AllSmart/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '10AvaliaMultMatrizes/reports/ds.seed1448.AllSmart/index.html'

18:25:09 - 11ListArray - ERROR: /reports/ds.seed1448.AllSmart/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '11ListArray/reports/ds.seed1448.AllSmart/index.html'

18:25:16 - 22TabelaHash - ERROR: /reports/ds.seed1448.AllSmart/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed1448.AllSmart/index.html'

18:25:16 - 23TabelaHash - ERROR: /reports/ds.seed1448.AllSmart/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '23TabelaHash/reports/ds.seed1448.AllSmart/index.html'

18:25:31 - 10AvaliaMultMatrizes - ERROR: /reports/ds.seed1448.AllSmart/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '10AvaliaMultMatrizes/reports/ds.seed1448.AllSmart/index.html'

19:03:19 - 11ListArray - ERROR: /reports/ds.seed1448.AllSmart/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '11ListArray/reports/ds.seed1448.AllSmart/index.html'

20:45:54 - 11ListArray - ERROR: /reports/ds.seed7992.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '11ListArray/reports/ds.seed7992.All/index.html'

21:09:08 - 12Lista - ERROR: /reports/ds.seed9006.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '12Lista/reports/ds.seed9006.All/index.html'

21:13:09 - 13Pilha - ERROR: /reports/ds.seed9006.AllSmart/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '13Pilha/reports/ds.seed9006.AllSmart/index.html'

21:17:48 - 14Pilha - ERROR: /reports/ds.seed5311.AllSmart/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '14Pilha/reports/ds.seed5311.AllSmart/index.html'

21:47:07 - 14Pilha - ERROR: /reports/ds.seed5838.AllSmart/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '14Pilha/reports/ds.seed5838.AllSmart/index.html'

21:48:47 - 14Pilha - ERROR: /reports/ds.seed5838.AllSmart/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '14Pilha/reports/ds.seed5838.AllSmart/index.html'

21:52:43 - 14Pilha - ERROR: /reports/ds.seed6733.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '14Pilha/reports/ds.seed6733.All/index.html'

21:56:13 - 14Pilha - ERROR: /reports/ds.seed6733.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '14Pilha/reports/ds.seed6733.All/index.html'

21:57:07 - 14Pilha - ERROR: /reports/ds.seed6733.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '14Pilha/reports/ds.seed6733.All/index.html'

22:00:37 - 14Pilha - ERROR: /reports/ds.seed9121.AllSmart/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '14Pilha/reports/ds.seed9121.AllSmart/index.html'

22:04:49 - 15Fila - ERROR: /reports/ds.seed5482.AllSmart/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '15Fila/reports/ds.seed5482.AllSmart/index.html'

22:08:02 - 16Fila - ERROR: /reports/ds.seed5311.AllSmart/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '16Fila/reports/ds.seed5311.AllSmart/index.html'

22:12:29 - 19FPHeapMin - ERROR: /reports/ds.seed1448.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '19FPHeapMin/reports/ds.seed1448.All/index.html'

22:15:04 - 19FPHeapMin - ERROR: /reports/ds.seed1448.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '19FPHeapMin/reports/ds.seed1448.All/index.html'

22:16:07 - 19FPHeapMin - ERROR: /reports/ds.seed1448.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '19FPHeapMin/reports/ds.seed1448.All/index.html'

22:18:57 - 19FPHeapMin - ERROR: /reports/ds.seed5311.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '19FPHeapMin/reports/ds.seed5311.All/index.html'

22:21:16 - 19FPHeapMin - ERROR: /reports/ds.seed5838.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '19FPHeapMin/reports/ds.seed5838.All/index.html'

22:23:17 - 19FPHeapMin - ERROR: /reports/ds.seed6733.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '19FPHeapMin/reports/ds.seed6733.All/index.html'

22:25:39 - 20Tabela - ERROR: /reports/ds.seed5503.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '20Tabela/reports/ds.seed5503.All/index.html'

22:29:49 - 22TabelaHash - ERROR: /reports/ds.seed1448.AllSmart/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed1448.AllSmart/index.html'

22:39:59 - 19FPHeapMin - ERROR: /reports/ds.seed5482.AllSmart/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '19FPHeapMin/reports/ds.seed5482.AllSmart/index.html'

22:42:33 - 22TabelaHash - ERROR: /reports/ds.seed5503.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed5503.All/index.html'

22:47:33 - 22TabelaHash - ERROR: /reports/ds.seed5831.AllSmart/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed5831.AllSmart/index.html'

22:48:46 - 22TabelaHash - ERROR: /reports/ds.seed5831.AllSmart/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed5831.AllSmart/index.html'

22:49:30 - 22TabelaHash - ERROR: /reports/ds.seed5831.AllSmart/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed5831.AllSmart/index.html'

22:53:15 - 22TabelaHash - ERROR: /reports/ds.seed6733.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed6733.All/index.html'

22:57:24 - 22TabelaHash - ERROR: /reports/ds.seed9006.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed9006.All/index.html'

22:58:03 - 22TabelaHash - ERROR: /reports/ds.seed9006.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed9006.All/index.html'

22:59:18 - 22TabelaHash - ERROR: /reports/ds.seed9006.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed9006.All/index.html'

22:59:54 - 22TabelaHash - ERROR: /reports/ds.seed9006.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed9006.All/index.html'

23:02:44 - 22TabelaHash - ERROR: /reports/ds.seed9121.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed9121.All/index.html'

23:05:20 - 23TabelaHash - ERROR: /reports/ds.seed9121.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '23TabelaHash/reports/ds.seed9121.All/index.html'

23:08:39 - 23TabelaHash - ERROR: /reports/ds.seed1448.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '23TabelaHash/reports/ds.seed1448.All/index.html'

23:09:29 - 23TabelaHash - ERROR: /reports/ds.seed1448.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '23TabelaHash/reports/ds.seed1448.All/index.html'

23:12:10 - 23TabelaHash - ERROR: /reports/ds.seed5311.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '23TabelaHash/reports/ds.seed5311.All/index.html'

23:15:24 - 23TabelaHash - ERROR: /reports/ds.seed5503.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '23TabelaHash/reports/ds.seed5503.All/index.html'

23:18:45 - 23TabelaHash - ERROR: /reports/ds.seed6733.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '23TabelaHash/reports/ds.seed6733.All/index.html'

23:20:13 - 23TabelaHash - ERROR: /reports/ds.seed6733.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '23TabelaHash/reports/ds.seed6733.All/index.html'

23:20:40 - 23TabelaHash - ERROR: /reports/ds.seed6733.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '23TabelaHash/reports/ds.seed6733.All/index.html'

23:21:11 - 23TabelaHash - ERROR: /reports/ds.seed6733.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '23TabelaHash/reports/ds.seed6733.All/index.html'

23:21:44 - 23TabelaHash - ERROR: /reports/ds.seed6733.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '23TabelaHash/reports/ds.seed6733.All/index.html'

23:33:49 - 26Grafo - ERROR: /reports/ds.seed5482.AllSmart/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '26Grafo/reports/ds.seed5482.AllSmart/index.html'

23:37:08 - 26Grafo - ERROR: /reports/ds.seed5482.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '26Grafo/reports/ds.seed5482.All/index.html'

23:55:46 - 26Grafo - ERROR: /reports/ds.seed5482.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '26Grafo/reports/ds.seed5482.All/index.html'

23:56:13 - 26Grafo - ERROR: /reports/ds.seed5482.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '26Grafo/reports/ds.seed5482.All/index.html'

23:56:51 - 26Grafo - ERROR: /reports/ds.seed5482.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '26Grafo/reports/ds.seed5482.All/index.html'

23:57:39 - 26Grafo - ERROR: /reports/ds.seed5482.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '26Grafo/reports/ds.seed5482.All/index.html'

00:11:03 - 26Grafo - ERROR: /reports/ds.seed5831.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '26Grafo/reports/ds.seed5831.All/index.html'

00:16:09 - 26Grafo - ERROR: /reports/ds.seed6733.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '26Grafo/reports/ds.seed6733.All/index.html'

00:22:35 - 26Grafo - ERROR: /reports/ds.seed6733.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '26Grafo/reports/ds.seed6733.All/index.html'

00:24:17 - 26Grafo - ERROR: /reports/ds.seed7992.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '26Grafo/reports/ds.seed7992.All/index.html'

00:34:31 - 26Grafo - ERROR: /reports/ds.seed9006.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '26Grafo/reports/ds.seed9006.All/index.html'

00:36:00 - 28BuscaEmLargura - ERROR: /reports/ds.seed6733.AllSmart/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '28BuscaEmLargura/reports/ds.seed6733.AllSmart/index.html'

00:39:54 - 28BuscaEmLargura - ERROR: /reports/ds.seed9006.AllSmart/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '28BuscaEmLargura/reports/ds.seed9006.AllSmart/index.html'

00:40:52 - 28BuscaEmLargura - ERROR: /reports/ds.seed9006.AllSmart/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '28BuscaEmLargura/reports/ds.seed9006.AllSmart/index.html'

00:44:50 - 29Grafo - ERROR: /reports/ds.seed5482.AllSmart/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '29Grafo/reports/ds.seed5482.AllSmart/index.html'

00:51:26 - 24Grafo - ERROR: /reports/ds.seed7992.AllSmart/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '24Grafo/reports/ds.seed7992.AllSmart/index.html'

16:33:11 - 22TabelaHash - ERROR: /reports/ds.seed1448.Palus/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed1448.Palus/index.html'

16:39:07 - 33Identifier - ERROR: /reports/ds.seed1448.Palus/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '33Identifier/reports/ds.seed1448.Palus/index.html'

16:52:13 - 22TabelaHash - ERROR: /reports/ds.seed5311.Palus/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed5311.Palus/index.html'

16:59:01 - 33Identifier - ERROR: /reports/ds.seed5311.Palus/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '33Identifier/reports/ds.seed5311.Palus/index.html'

17:17:24 - 33Identifier - ERROR: /reports/ds.seed5482.Palus/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '33Identifier/reports/ds.seed5482.Palus/index.html'

17:30:01 - 22TabelaHash - ERROR: /reports/ds.seed5503.Palus/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed5503.Palus/index.html'

17:35:48 - 33Identifier - ERROR: /reports/ds.seed5503.Palus/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '33Identifier/reports/ds.seed5503.Palus/index.html'

17:47:51 - 22TabelaHash - ERROR: /reports/ds.seed5831.Palus/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed5831.Palus/index.html'

17:53:53 - 33Identifier - ERROR: /reports/ds.seed5831.Palus/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '33Identifier/reports/ds.seed5831.Palus/index.html'

18:07:40 - 22TabelaHash - ERROR: /reports/ds.seed5838.Palus/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed5838.Palus/index.html'

18:13:59 - 33Identifier - ERROR: /reports/ds.seed5838.Palus/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '33Identifier/reports/ds.seed5838.Palus/index.html'

18:26:29 - 22TabelaHash - ERROR: /reports/ds.seed6733.Palus/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed6733.Palus/index.html'

18:32:36 - 33Identifier - ERROR: /reports/ds.seed6733.Palus/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '33Identifier/reports/ds.seed6733.Palus/index.html'

18:44:28 - 22TabelaHash - ERROR: /reports/ds.seed7992.Palus/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed7992.Palus/index.html'

18:50:31 - 33Identifier - ERROR: /reports/ds.seed7992.Palus/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '33Identifier/reports/ds.seed7992.Palus/index.html'

19:03:02 - 22TabelaHash - ERROR: /reports/ds.seed9006.Palus/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed9006.Palus/index.html'

19:09:12 - 33Identifier - ERROR: /reports/ds.seed9006.Palus/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '33Identifier/reports/ds.seed9006.Palus/index.html'

19:21:19 - 22TabelaHash - ERROR: /reports/ds.seed9121.Palus/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed9121.Palus/index.html'

19:27:30 - 33Identifier - ERROR: /reports/ds.seed9121.Palus/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '33Identifier/reports/ds.seed9121.Palus/index.html'

21:44:13 - 22TabelaHash - ERROR: /reports/ds.seed1448.Palus/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed1448.Palus/index.html'

21:45:13 - 22TabelaHash - ERROR: /reports/ds.seed1448.Palus/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed1448.Palus/index.html'

21:54:56 - 22TabelaHash - ERROR: /reports/ds.seed5831.Palus/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed5831.Palus/index.html'

21:55:15 - 22TabelaHash - ERROR: /reports/ds.seed5831.Palus/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed5831.Palus/index.html'

21:57:08 - 22TabelaHash - ERROR: /reports/ds.seed5831.Palus/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed5831.Palus/index.html'

21:57:52 - 22TabelaHash - ERROR: /reports/ds.seed5831.Palus/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed5831.Palus/index.html'

21:58:26 - 22TabelaHash - ERROR: /reports/ds.seed5831.Palus/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed5831.Palus/index.html'

22:00:07 - 22TabelaHash - ERROR: /reports/ds.seed5838.Palus/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed5838.Palus/index.html'

22:01:13 - 22TabelaHash - ERROR: /reports/ds.seed6733.Palus/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed6733.Palus/index.html'

22:02:30 - 22TabelaHash - ERROR: /reports/ds.seed7992.Palus/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed7992.Palus/index.html'

22:02:44 - 22TabelaHash - ERROR: /reports/ds.seed7992.Palus/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed7992.Palus/index.html'

22:03:01 - 22TabelaHash - ERROR: /reports/ds.seed7992.Palus/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed7992.Palus/index.html'

22:03:19 - 22TabelaHash - ERROR: /reports/ds.seed7992.Palus/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed7992.Palus/index.html'

22:03:34 - 22TabelaHash - ERROR: /reports/ds.seed7992.Palus/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed7992.Palus/index.html'

22:03:55 - 22TabelaHash - ERROR: /reports/ds.seed7992.Palus/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed7992.Palus/index.html'

22:04:11 - 22TabelaHash - ERROR: /reports/ds.seed7992.Palus/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed7992.Palus/index.html'

22:06:32 - 22TabelaHash - ERROR: /reports/ds.seed9006.Palus/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed9006.Palus/index.html'

22:06:47 - 22TabelaHash - ERROR: /reports/ds.seed9006.Palus/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed9006.Palus/index.html'

22:08:31 - 22TabelaHash - ERROR: /reports/ds.seed9121.Palus/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed9121.Palus/index.html'

22:08:47 - 22TabelaHash - ERROR: /reports/ds.seed9121.Palus/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed9121.Palus/index.html'

22:09:51 - 22TabelaHash - ERROR: /reports/ds.seed9121.Palus/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '22TabelaHash/reports/ds.seed9121.Palus/index.html'

22:11:09 - 33Identifier - ERROR: /reports/ds.seed1448.Palus/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '33Identifier/reports/ds.seed1448.Palus/index.html'

22:11:31 - 33Identifier - ERROR: /reports/ds.seed1448.Palus/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '33Identifier/reports/ds.seed1448.Palus/index.html'

22:20:38 - 33Identifier - ERROR: /reports/ds.seed1448.Palus/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '33Identifier/reports/ds.seed1448.Palus/index.html'

22:24:47 - 33Identifier - ERROR: /reports/ds.seed1448.Palus/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '33Identifier/reports/ds.seed1448.Palus/index.html'

22:27:28 - 33Identifier - ERROR: /reports/ds.seed1448.Palus/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '33Identifier/reports/ds.seed1448.Palus/index.html'

22:28:18 - 33Identifier - ERROR: /reports/ds.seed1448.Palus/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '33Identifier/reports/ds.seed1448.Palus/index.html'

22:32:10 - 33Identifier - ERROR: /reports/ds.seed1448.Palus/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '33Identifier/reports/ds.seed1448.Palus/index.html'

22:33:40 - 33Identifier - ERROR: /reports/ds.seed1448.Palus/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '33Identifier/reports/ds.seed1448.Palus/index.html'

22:34:55 - 33Identifier - ERROR: /reports/ds.seed1448.Palus/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '33Identifier/reports/ds.seed1448.Palus/index.html'

22:35:19 - 33Identifier - ERROR: /reports/ds.seed1448.Palus/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '33Identifier/reports/ds.seed1448.Palus/index.html'

22:37:21 - 33Identifier - ERROR: /reports/ds.seed1448.Palus/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '33Identifier/reports/ds.seed1448.Palus/index.html'

22:37:40 - 33Identifier - ERROR: /reports/ds.seed1448.Palus/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '33Identifier/reports/ds.seed1448.Palus/index.html'

22:46:53 - 33Identifier - ERROR: /reports/ds.seed1448.Palus/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '33Identifier/reports/ds.seed1448.Palus/index.html'

22:47:52 - 33Identifier - ERROR: /reports/ds.seed1448.Palus/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '33Identifier/reports/ds.seed1448.Palus/index.html'

23:05:42 - 33Identifier - ERROR: /reports/ds.seed7992.Palus/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '33Identifier/reports/ds.seed7992.Palus/index.html'

14:49:56 - 26Grafo - ERROR: /reports/ds.seed6733.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '26Grafo/reports/ds.seed6733.All/index.html'

15:41:50 - 26Grafo - ERROR: /reports/ds.seed7992.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '26Grafo/reports/ds.seed7992.All/index.html'

16:35:27 - 26Grafo - ERROR: /reports/ds.seed9006.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '26Grafo/reports/ds.seed9006.All/index.html'

19:57:11 - 26Grafo - ERROR: /reports/ds.seed6733.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '26Grafo/reports/ds.seed6733.All/index.html'

20:01:40 - 26Grafo - ERROR: /reports/ds.seed6733.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '26Grafo/reports/ds.seed6733.All/index.html'

20:07:20 - 26Grafo - ERROR: /reports/ds.seed7992.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '26Grafo/reports/ds.seed7992.All/index.html'

20:15:20 - 26Grafo - ERROR: /reports/ds.seed9006.All/index.html
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    with open(prj+"/reports/"+test+"/index.html",'r') as html:
IOError: [Errno 2] No such file or directory: '26Grafo/reports/ds.seed9006.All/index.html'

